default: ScreenString.out


ScreenString.out: ScreenString.c
	gcc ScreenString.c -o ScreenString.o -c -Wextra -Wall

error.txt: ScreenString.c
	gcc ScreenString.c -o ScreenString.o -c -Wextra -Wall 2> error.txt